### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by Sandakan** [Seniru/Calculator#3]
Sounds makes your code slow. And even it consumes more data. Most popular calculators won't use sounds.

**Comment by Seniru** [comment]
So do you have any suggestion?
I made this specially for people with deficiencies and also this would help to minimize mistakes

**Comment by Seniru** [comment]
@Sandakan I created a solution for your problem. Please take a look at it and say is it OK for the users.
https://github.com/Seniru/Calculator/tree/Sound_Features

**Comment by Seniru** [comment]
Closing the issue because of inactivity and because the issue has been solved
