### ISSUE TITLE
1.1 + 1.3 != 2.4000000000000004

### ISSUE THREAD

**Issue by salif** [Seniru/Calculator#5]
Hi, 1.1 + 1.3 is equal to 2.4, but calculator shows 2.4000000000000004

Screenshot:
![Screenshot from 2019-08-21 22-59-45](https://user-images.githubusercontent.com/35408721/63464190-65329480-c467-11e9-8ba2-7dcec210de67.png)

**Comment by Seniru** [comment]
Thanks for reporting this bug. 
This is a problem with js regarding additions. But I'm actively finding a way to fix this issue.

**Comment by Seniru** [comment]
@salifm I couldn't find a way to solve this problem unfortunately. This issue is open to anyone who likes to solve this.

**Comment by Seniru** [comment]
Since this is a problem with js and nobody is working to fix it I decided to close this issue. But anybody who would like to fix this issue could work on this
